### ISSUE TITLE
[PE-D][Tester D] Editing a person to have the same name as another existing person

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F12-1/tp#160]
In the UG under Editing a person, it is stated that **any value is possible** for NAME. But, the app does not allow for duplicate contacts and will return "This person already exists in the address book." if we try to edit a contact to have the same name.

![image.png](https://raw.githubusercontent.com/glenngnng/ped/main/files/3cf6ca61-6564-4a14-bc47-b1c652c033dc.png)

Perhaps can change the UG description to indicate that editing name to an existing person's name is invalid?

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: glenngnng/ped#2

**Comment by sopa301** [comment]
the current behavior inconveniences the user but there is a way to work around it (i.e. searching for the name first before using it). Will make it more explicit in the UG.
