### ISSUE TITLE
[PE-D][Tester D] Possible to add appointment dates before the current date

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F12-1/tp#177]
In the app, it is possible to add an appointment date which is supposedly invalid, like a date that has passed. 

Currently, it is 3rd nov, but it is possible to schedule 2nd feb. This might result in incorrect dates input accidentally by financial advisors.

![image.png](https://raw.githubusercontent.com/glenngnng/ped/main/files/8d2a9b0d-a983-46e4-a22b-817b41418ed6.png)

Perhaps, the same error message shown when there is an invalid time input, e.g 29:00, can be shown to the user for a possibly invalid date.

![image.png](https://raw.githubusercontent.com/glenngnng/ped/main/files/3a5f913c-006b-4e64-87e5-f42e58477564.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: glenngnng/ped#7

**Comment by sopa301** [comment]
the current behavior is not strictly 'incorrect' but 'can be better'. Will indicate as a planned enhancement.
