### ISSUE TITLE
Updating json file with "leap year dates" still has issue

### ISSUE THREAD

**Issue by jylow** [AY2324S1-CS2103T-F12-1/tp#263]
Previous issue was fixed with the leap year date thing. However, when json file is changed to include 31-02-2001 or any such not allowed dates, the system still allows parsing and sets the date at the closest date before. 

Conversely, changing date to 13-13-2000 will result in an exception being thrown and the file not being able to be opened. Such an issue should be documented in the UG as well.

**Comment by sopa301** [comment]
As mentioned, we can specify this in the UG.
