### ISSUE TITLE
financial plan tag does not wrap around for long tag

### ISSUE THREAD

**Issue by jylow** [AY2324S1-CS2103T-F12-1/tp#268]
Unlike email, address and phone number, financial plan tag does not "wrap" when exitting frame. As a result, it instead extends the frame, causing the border to be outside of the display area. This in turn results in the address, phone number and email no longer wrapping around and long strings will be lost past the edge

**Comment by sopa301** [comment]
This is a known issue, and has been identified in the known issues in UG and future improvements in DG

**Comment by sopa301** [comment]
I managed to fix the issue and make it wrap. Need to update UG DG
